import { Button, VerticalBox, StandardTableView, Slider, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    full-screen: true;
    in-out property <string> counter: "";
    in-out property <string> id;
    callback submit-id();

    VerticalBox {
        alignment: center;
        Text {
            text: "Type your 6-digit numerical ID here:";
        }
        LineEdit {
            text <=> id;
            input-type: password;
        }
        Button {
            text: "Submit";
            clicked => {
                root.submit-id();
            }
        }
        error-message := Text {
            text: "Error: Malformed ID";
            visible: false;
            color: #ed2409;
        }
    }
    callback show-error();
    show-error => {
        error-message.visible = true;
    }
}
